// The environment contract, declared once.
//
// It used to be written in ten places - four doc tables, two READMEs,
// .env.example, .env.docusign.example, the k8s secret and the Cloudflare
// config - and generated by none, so they drifted. Worse, all ten answered
// only "what does this do". The question an operator actually has is "how do
// I obtain this value", and that was answered for DOCUSIGN_* and nothing
// else.
//
// So: one entry per variable, carrying why it exists, how the service uses
// it, and how to get it. `render.ts` turns this into the .env example, the
// doc tables and the deploy manifest comments; two checks
// (tests/env-registry.test.ts) fail if a variable is read without an entry,
// or if an operator-supplied value has no howToObtain.
//
// Variables that name another system keep their own names and appear here
// too - an operator has to set DOCUSIGN_* as much as ESIGN_*.

export type Runtime = 'node' | 'vercel' | 'cloudflare';

// Who has to know about this variable. 'backend' is one a host developer
// meets while writing code against the package; 'operator' is one someone
// setting up a deployment has to supply.
export type Audience = 'operator' | 'backend' | 'both';

export interface EnvVar {
  name: string;
  // What breaks, or what is silently permitted, without it
  why: string;
  // What the service does with the value, so a reader can predict behaviour
  usedFor: string;
  // Where the value comes from. Required for anything an operator supplies
  // that has no default - a worked path, not a restatement of the name.
  howToObtain?: string;
  // When it is needed at all
  requiredWhen: string;
  // What happens when it is unset
  default?: string;
  targets: Runtime[];
  audience: Audience;
}

const EVERY: Runtime[] = ['node', 'vercel', 'cloudflare'];
const NODE_ONLY: Runtime[] = ['node'];

// --- Capabilities ------------------------------------------------------------

const capabilities: EnvVar[] = [
  {
    name: 'DATABASE_URL',
    why: 'Decides whether this deployment orchestrates envelopes at all. Unset, the mint is the whole service and no Postgres connection is opened.',
    usedFor:
      'capabilities.ts switches on /graphql, POST /webhook/esign and the Knex store when it holds a value',
    howToObtain:
      'Your Postgres connection string. Apply the schema once with:\n  node dist/node.js migrate',
    requiredWhen: 'envelope orchestration is wanted',
    default: 'unset - the mint alone, on every target',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_MINT_MODE',
    why: 'Which of the two mints this deployment answers with. They are different products: a Web Form asks the signer questions first, an envelope puts them straight into the documents.',
    usedFor: 'mint.ts selects the route (POST /webform/instance or POST /envelope/instance)',
    requiredWhen: 'never',
    default: "'webform'",
    targets: EVERY,
    audience: 'both',
  },
  {
    name: 'ESIGN_PROVIDER',
    why: 'Which e-signature provider mints. The mock needs no credentials and signs nothing that holds.',
    usedFor: "providers/index.ts selects the adapter; 'mock' or 'docusign'",
    requiredWhen: 'never',
    default: "'mock' - which the boot banner reports as a demo provider",
    targets: EVERY,
    audience: 'both',
  },
];

// --- Session verification ----------------------------------------------------

const session: EnvVar[] = [
  {
    name: 'ESIGN_SESSION_JWKS_URL',
    why: "Verifies that a caller's bearer token really came from your login provider. Without a session source the service cannot tell one user from another: it takes the token as the user id.",
    usedFor:
      "session.ts fetches the public keys and checks each token's signature, then its exp, issuer and audience",
    howToObtain:
      'Your identity provider publishes it. Take jwks_uri from its discovery document:\n' +
      '  curl -s https://<issuer>/.well-known/openid-configuration | jq -r .jwks_uri\n' +
      'Auth0, Okta, Cognito, Keycloak and Firebase all have one. If your own backend\n' +
      'issues the tokens, use ESIGN_SESSION_SECRET instead - it is an equal, not a\n' +
      'fallback. Confirm it with:\n' +
      '  node dist/node.js check-session "$TOKEN"',
    requiredWhen: 'never - the banner reports an unverified session, ESIGN_STRICT refuses one',
    default: 'unset - see ESIGN_SESSION_SECRET, then the note above',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_SESSION_SECRET',
    why: 'The same verification, for a backend that issues its own tokens and signs them with a shared secret.',
    usedFor: 'session.ts verifies each token as HS256 against it',
    howToObtain:
      'The secret your own backend signs session tokens with - the same value, not a new one.\n' +
      'Prefer ESIGN_SESSION_JWKS_URL when you have an identity provider: this service then\n' +
      'holds no signing material and cannot mint tokens even if it is compromised.',
    requiredWhen: 'never - one of the two session sources',
    default: 'unset',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_SESSION_ISSUER',
    why: 'Pins which issuer a token may come from. Without it any token your key material verifies is accepted, whoever issued it.',
    usedFor: "session.ts requires the token's iss to equal it",
    howToObtain:
      'The iss claim of a real token, copied exactly:\n' +
      '  echo "$TOKEN" | cut -d. -f2 | base64 -d | jq -r .iss\n' +
      'Trailing slashes count. check-session names both sides when they differ.',
    requiredWhen: 'never, but set it',
    default: 'unset - the issuer is not checked',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_SESSION_AUDIENCE',
    why: 'Pins which audience a token was minted for, so a token issued for another service of yours is not accepted here.',
    usedFor: "session.ts requires the token's aud to include it",
    howToObtain:
      'The aud claim of a real token:\n' + '  echo "$TOKEN" | cut -d. -f2 | base64 -d | jq -r .aud',
    requiredWhen: 'never, but set it',
    default: 'unset - the audience is not checked',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_SESSION_USER_CLAIM',
    why: 'Which claim carries your user id. DocuSign sees this value as clientUserId, so it is what ties a signature to a person.',
    usedFor: 'session.ts reads the user id from this claim of the verified payload',
    howToObtain:
      'Look at a real token and pick the claim holding your user id:\n' +
      '  echo "$TOKEN" | cut -d. -f2 | base64 -d | jq',
    requiredWhen: 'the user id is not in sub',
    default: "'sub'",
    targets: EVERY,
    audience: 'operator',
  },
];

// --- The prefill callback ----------------------------------------------------

const prefill: EnvVar[] = [
  {
    name: 'ESIGN_PREFILL_URL',
    why: "Decides who computes the values a signer cannot change. Unset, the client's own prefill is minted as sent - which is fine for a fixed consent form and wrong for anything whose fields carry the deal.",
    usedFor:
      "prefill.ts POSTs { userId, input } here with the caller's bearer forwarded; the reply's { prefill } is what gets minted",
    howToObtain:
      'An endpoint on your own backend that you write. It receives\n' +
      '  { userId, input }        (an envelope mint also sends recipient)\n' +
      'and answers\n' +
      '  { prefill: { ... } }     (and, for an envelope, an optional recipient)\n' +
      'Confirm it answers correctly with:\n' +
      '  node dist/node.js check-prefill',
    requiredWhen: 'never - the banner reports client-supplied terms, ESIGN_STRICT refuses them',
    default: "unset - the client's prefill is minted as sent",
    targets: EVERY,
    audience: 'both',
  },
  {
    name: 'ESIGN_PREFILL_SECRET',
    why: 'Lets your prefill endpoint tell this service apart from anything else that finds the URL.',
    usedFor: 'prefill.ts sends it as the x-esign-prefill-secret header',
    howToObtain:
      'Any high-entropy string you also configure on the receiving endpoint:\n' +
      '  openssl rand -hex 32',
    requiredWhen: 'never, but set it when the callback is reachable beyond your own network',
    default: 'unset - the header is not sent',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_PREFILL_TIMEOUT_MS',
    why: 'Bounds how long a mint waits on your backend before answering 502.',
    usedFor: 'prefill.ts aborts the callback after this many milliseconds',
    requiredWhen: 'never',
    default: '5000',
    targets: EVERY,
    audience: 'operator',
  },
];

// --- Posture -----------------------------------------------------------------

const posture: EnvVar[] = [
  {
    name: 'ESIGN_STRICT',
    why: 'Turns every line the boot banner reports as unverified into a refusal to start. Off by default because what an unverified session or a client-supplied prefill means depends on your architecture, which this process cannot see.',
    usedFor:
      'config.ts refuses to boot, naming the variable that fixes each gap; server.ts also refuses to listen on a failed preflight probe',
    requiredWhen: 'never',
    default: 'unset - the service reports its posture and starts',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_GRAPHQL_INTROSPECTION',
    why: "Apollo's schema discovery. Off by default so a deployment does not publish its schema without saying so.",
    usedFor: 'app.ts passes it to the Apollo server when envelopes are on',
    requiredWhen: 'never',
    default: 'unset - introspection is off',
    targets: NODE_ONLY,
    audience: 'backend',
  },
];

// --- DocuSign ----------------------------------------------------------------

const CONSOLE =
  'DocuSign Admin -> Apps and Keys. The full click path, including the consent step that is easy to miss, is docs/integration/docusign-proxy.md.';

const docusign: EnvVar[] = [
  {
    name: 'DOCUSIGN_INTEGRATION_KEY',
    why: 'Identifies your application to DocuSign. Without the JWT-grant credentials nothing can be minted.',
    usedFor: 'the JWT grant, as the client id',
    howToObtain: `${CONSOLE} The integration key is the GUID shown on the app.`,
    requiredWhen: 'ESIGN_PROVIDER=docusign',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_ACCOUNT_ID',
    why: 'Which DocuSign account the envelopes and instances belong to.',
    usedFor: 'every DocuSign API path',
    howToObtain:
      'DocuSign Admin -> Account -> API and Keys: the "API Account ID" GUID, not the account number.',
    requiredWhen: 'ESIGN_PROVIDER=docusign',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_USER_ID',
    why: 'Whom the service impersonates. Envelopes are sent as this user.',
    usedFor: 'the JWT grant, as the subject',
    howToObtain:
      'DocuSign Admin -> Users -> the service user -> "API Username" (a GUID). That user must have granted consent once.',
    requiredWhen: 'ESIGN_PROVIDER=docusign',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_PRIVATE_KEY',
    why: 'Proves the service is the integration key it claims to be. The only DocuSign value that is a secret.',
    usedFor: 'signs the JWT grant assertion (RS256)',
    howToObtain:
      'Generate a keypair, upload the public half on the integration key:\n' +
      '  openssl genrsa -out esign.pem 2048 && openssl rsa -in esign.pem -pubout\n' +
      `Paste the private PEM verbatim. ${CONSOLE}\n` +
      'Alternatives: DOCUSIGN_PRIVATE_KEY_BASE64 (every target),\n' +
      'DOCUSIGN_PRIVATE_KEY_FILE (a container secret mount).',
    requiredWhen: 'ESIGN_PROVIDER=docusign',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_PRIVATE_KEY_BASE64',
    why: 'The same key where a multi-line environment value is awkward.',
    usedFor: 'decoded, then used exactly as DOCUSIGN_PRIVATE_KEY',
    howToObtain: '  base64 -i esign.pem',
    requiredWhen: 'instead of DOCUSIGN_PRIVATE_KEY',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_PRIVATE_KEY_FILE',
    why: 'The same key from a mounted secret, so it never appears in the environment.',
    usedFor: 'read from disk at selection time',
    howToObtain:
      'The path a secret is mounted at, e.g. /run/secrets/docusign.pem. Container-only: a Worker has no filesystem.',
    requiredWhen: 'instead of DOCUSIGN_PRIVATE_KEY',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_WEBFORM_ID',
    why: 'Which Web Form the mint creates an instance of.',
    usedFor: 'POST /webform/instance',
    howToObtain: 'DocuSign -> Web Forms -> the form -> its id in the URL. The form must be active.',
    requiredWhen: 'the Web Form mint (ESIGN_MINT_MODE=webform)',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_TEMPLATE_ID',
    why: 'Which template(s) an envelope is created from.',
    usedFor:
      'the envelope mint and envelope orchestration; several ids, comma-separated, go out as one envelope in that order',
    howToObtain:
      'DocuSign -> Templates -> the template -> its id. `make docusign-template` creates the fixture one and prints its id.',
    requiredWhen: 'ESIGN_MINT_MODE=envelope, or envelope orchestration',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_RETURN_URL',
    why: "Where DocuSign sends the signer afterwards. It must reach this service's bridge, which is what reports completion back to your app.",
    usedFor: 'passed on every mint; the bridge is GET /signing/return',
    howToObtain:
      "This deployment's public URL plus /signing/return. It has to be reachable by the signer's browser, not just by the service.",
    requiredWhen: 'ESIGN_PROVIDER=docusign',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_SIGNER_ROLE',
    why: 'Which template role the signer fills.',
    usedFor: 'the envelope mint',
    howToObtain: 'The role name on the template, as spelled there.',
    requiredWhen: 'the template role is not named signer',
    default: "'signer'",
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_HMAC_KEY',
    why: "Proves an inbound webhook really came from DocuSign. Without it anyone who finds the URL can write 'completed' into your envelope records.",
    usedFor: 'verifies the Connect signature on POST /webhook/esign',
    howToObtain:
      'DocuSign Admin -> Connect -> your configuration -> Add HMAC key. DocuSign shows the secret once.',
    requiredWhen: 'envelope orchestration is on',
    default: 'unset - the banner reports an unverified webhook',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_BASE_URL',
    why: 'Which DocuSign environment this is. The default is the demo one, which signs nothing that holds up.',
    usedFor: 'the REST API host',
    howToObtain:
      "DocuSign Admin -> API and Keys shows your account's base URI, e.g.\n" +
      '  https://na4.docusign.net/restapi\n' +
      'The region prefix differs per account.',
    requiredWhen: 'a production DocuSign account',
    default: 'the demo host - reported as a sandbox by the boot banner',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_OAUTH_URL',
    why: 'Where the JWT grant is exchanged. It has to match the environment of the account.',
    usedFor: 'the OAuth host',
    howToObtain: 'https://account.docusign.com for production; the default is the demo host.',
    requiredWhen: 'a production DocuSign account',
    default: 'the demo host',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'DOCUSIGN_WEBFORMS_BASE_URL',
    why: 'Where Web Forms instances are minted. Same environment rule again.',
    usedFor: 'the Web Forms API host',
    howToObtain:
      'https://apps.docusign.com/api/webforms/v1.1 for production; the default is the demo host.',
    requiredWhen: 'a production DocuSign account',
    default: 'the demo host',
    targets: EVERY,
    audience: 'operator',
  },
];

// --- Deployment --------------------------------------------------------------

const deployment: EnvVar[] = [
  {
    name: 'PORT',
    why: 'Which port the Node target listens on. A function target is told by its platform.',
    usedFor: 'server.ts binds it',
    requiredWhen: 'never',
    default: 'ESIGN_PORT_BASE (4100)',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_PORT_BASE',
    why: 'The base every service in this repo derives its port from, so parallel worktrees do not collide.',
    usedFor: 'port.ts and scripts/lib/ports.mjs',
    requiredWhen: 'never',
    default: '4100',
    targets: NODE_ONLY,
    audience: 'backend',
  },
  {
    name: 'ESIGN_TRUST_PROXY',
    why: 'Whether x-forwarded-for may be believed. It is a caller-controlled header, so believing it without a proxy in front lets anyone spoof their address past the rate limits.',
    usedFor: 'proxy.ts decides the client address for the rate limits and the webhook security log',
    howToObtain:
      'Set it to true only when something you control terminates connections in front of this service.',
    requiredWhen: 'behind a load balancer or ingress',
    default: 'unset - x-forwarded-for is ignored',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_CORS_ALLOWED_ORIGINS',
    why: 'Which browser origins may call the mint and the GraphQL API.',
    usedFor: 'config.ts; comma-separated, empty means same-origin only',
    howToObtain: 'The origins of your own web app, e.g. https://app.example.com.',
    requiredWhen: 'a browser calls this service cross-origin',
    default: 'unset - same-origin only',
    targets: EVERY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_RATE_LIMIT_WEBFORM_PER_MIN',
    why: 'Caps mints per client per minute. Each one costs a real DocuSign instance.',
    usedFor: 'server.ts; 0 switches the route limit off',
    requiredWhen: 'never',
    default: '60',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_RATE_LIMIT_ENVELOPE_PER_MIN',
    why: 'The same cap for the envelope mint.',
    usedFor: 'server.ts; 0 switches the route limit off',
    requiredWhen: 'never',
    default: '60',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_RATE_LIMIT_WEBHOOK_PER_MIN',
    why: 'Caps inbound webhooks, which arrive unauthenticated until the signature is checked.',
    usedFor: 'server.ts; 0 switches the route limit off',
    requiredWhen: 'never',
    default: '120',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_RATE_LIMIT_GRAPHQL_PER_MIN',
    why: 'Caps GraphQL requests per client.',
    usedFor: 'server.ts; 0 switches the route limit off',
    requiredWhen: 'never',
    default: '100',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'ESIGN_MOCK_PAGES',
    why: 'Whether the mock provider serves its own signing pages. A deployment that only wants the mint surface turns them off.',
    usedFor: 'capabilities.ts; false removes the pages even for the mock',
    requiredWhen: 'never',
    default: 'on for the mock provider',
    targets: EVERY,
    audience: 'backend',
  },
  {
    name: 'ESIGN_MOCK_PAGES_ORIGIN',
    why: "Where the mock's signing URLs point, when it is not this service's own origin.",
    usedFor: 'the mock adapter builds instance URLs on it',
    requiredWhen: 'never',
    default: "this service's own origin",
    targets: EVERY,
    audience: 'backend',
  },
];

// --- Observability -----------------------------------------------------------

const observability: EnvVar[] = [
  {
    name: 'OTEL_EXPORTER_OTLP_ENDPOINT',
    why: 'Turns tracing on. Off unless set, so no deployment ships spans it did not ask for.',
    usedFor: 'instrumentation.ts initialises the OTLP exporter',
    howToObtain:
      "Your collector's OTLP endpoint, e.g. http://localhost:4318. Any OTLP backend works.",
    requiredWhen: 'tracing is wanted',
    default: 'unset - tracing off',
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'OTEL_SERVICE_NAME',
    why: 'What this service is called in traces.',
    usedFor: 'the resource attributes',
    requiredWhen: 'never',
    default: "'esign-service'",
    targets: NODE_ONLY,
    audience: 'operator',
  },
  {
    name: 'OTEL_TRACES_EXPORTER',
    why: 'Prints spans to stdout instead of shipping them, for debugging without a collector.',
    usedFor: "instrumentation.ts; 'console' selects the console exporter",
    requiredWhen: 'never',
    default: 'unset',
    targets: NODE_ONLY,
    audience: 'backend',
  },
  {
    name: 'NODE_ENV',
    why: "Node's own switch (dependency resolution, framework defaults). It decides nothing about this service's posture - ESIGN_STRICT does.",
    usedFor: 'nothing in this service reads it',
    requiredWhen: 'never',
    default: "'production' in the image",
    targets: NODE_ONLY,
    audience: 'backend',
  },
];

export const REGISTRY: readonly EnvVar[] = [
  ...capabilities,
  ...session,
  ...prefill,
  ...posture,
  ...docusign,
  ...deployment,
  ...observability,
];
