// The two checks that keep the environment contract honest.
//
// Before this, the contract was written in ten places and generated by none,
// so it drifted; and none of those places said where a value comes from,
// which is the operator's whole question. These make both failures loud: a
// variable read without an entry, and an operator-supplied value with no
// how-to-obtain, are test failures rather than something noticed later.

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

import { REGISTRY } from '../src/env/registry';

const SRC = join(__dirname, '..', 'src');

const NAMES = new Set(REGISTRY.map((entry) => entry.name));

// Uppercase identifiers that are not environment variables: jose's error
// codes, JWS algorithms, HTTP methods and header values, process signals.
const NOT_ENV =
  /^(ERR_|SIG|RS\d|ES\d|PS\d|HS\d|GET|POST|PUT|HEAD|PATCH|DELETE|OPTIONS|DENY|MINT|ENVELOPES|DOCUSIGN_DEMO_URLS|DOCUSIGN_PRIVATE_KEY_SOURCES|DOCUSIGN_SCOPES|DOCUSIGN_SIGNATURE_HEADER|DOCUSIGN_ENV|RATE_LIMIT_(WINDOW_MS|MAX_WINDOWS)|DEFAULT_|JWKS_ALGORITHMS|PREFILL_|SESSION_|LABEL_WIDTH|SECURITY_HEADERS|TIMEOUT_MS|CONTROL_CHARS|JWT_CREDENTIALS|HOSTED_FORM_SETTINGS|ENVELOPE_SETTINGS|MINT_MODE_NAMES|MINT_MODES|CONSOLE|EVERY|NODE_ONLY|SRC|NAMES|NOT_ENV|REGISTRY|FIX|CASES)/;

const sourceFiles = (dir: string): string[] =>
  readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      return sourceFiles(path);
    }
    return path.endsWith('.ts') ? [path] : [];
  });

// Every read of the environment: `env['X']`, `env.X`, and `env[X]` where X
// is a constant - which is how most of this codebase does it, the constant
// being declared equal to its own name.
const readsFromSource = (): Set<string> => {
  const reads = new Set<string>();
  for (const file of sourceFiles(SRC)) {
    // The registry declares them; it does not read them
    if (file.includes(join('env', 'registry.ts'))) {
      continue;
    }
    const text = readFileSync(file, 'utf8');
    for (const [, bracket, dotted] of text.matchAll(
      /env\[['"]?([A-Z][A-Z0-9_]+)['"]?\]|env\.([A-Z][A-Z0-9_]+)/g
    )) {
      const name = bracket ?? dotted;
      if (name && !NOT_ENV.test(name)) {
        reads.add(name);
      }
    }
  }
  return reads;
};

describe('the environment registry', () => {
  // "You added a variable and told nobody" is the failure this prevents
  it('has an entry for every variable the source reads', () => {
    const missing = [...readsFromSource()].filter((name) => !NAMES.has(name)).sort();
    expect(missing).toEqual([]);
  });

  // The emptiest column in the old docs, now required
  it('tells an operator how to obtain every value they must supply', () => {
    const undocumented = REGISTRY.filter(
      (entry) => entry.audience !== 'backend' && !entry.default && !entry.howToObtain
    ).map((entry) => entry.name);
    expect(undocumented).toEqual([]);
  });

  it('says what happens without every variable that has no default', () => {
    const silent = REGISTRY.filter((entry) => !entry.default && !entry.requiredWhen).map(
      (entry) => entry.name
    );
    expect(silent).toEqual([]);
  });

  it('says which targets support each variable', () => {
    expect(REGISTRY.filter((entry) => entry.targets.length === 0)).toEqual([]);
  });

  it('declares each variable once', () => {
    expect(NAMES.size).toBe(REGISTRY.length);
  });

  it('explains why each variable exists and what reads it', () => {
    const thin = REGISTRY.filter((entry) => entry.why.length < 20 || entry.usedFor.length < 10).map(
      (entry) => entry.name
    );
    expect(thin).toEqual([]);
  });

  // The gate has to be able to fail, or it is decoration
  it('would notice a variable that has no entry', () => {
    const invented = 'ESIGN_NOT_IN_THE_REGISTRY';
    expect(NAMES.has(invented)).toBe(false);
    expect([invented].filter((name) => !NAMES.has(name))).toEqual([invented]);
  });
});
