# Deploy the esign service on NixOS as an OCI container. The only input is
# environment:
#
#   1. copy this file into the host configuration and import it
#   2. write the environment file (the ../.env.example contract) to
#      /run/secrets/esign.env - root-owned, 0400, or generated by
#      agenix / sops-nix
#   3. nixos-rebuild switch
#
# With ESIGN_PROVIDER=docusign, put the private key on the host as
# /run/secrets/docusign.pem (same handling as the env file): it is mounted
# read-only and named by DOCUSIGN_PRIVATE_KEY_FILE (the container-only way;
# DOCUSIGN_PRIVATE_KEY_BASE64 in the env file works everywhere).
#
# Capabilities follow DATABASE_URL in the env file: leave it unset for the
# mint alone, point it at Postgres for envelope orchestration. `migrate`
# applies the schema once per database (commented block at the bottom).
#
# This template is written against the NixOS options as documented; it has
# not been run against a live NixOS host.

{ ... }:

{
  # Either backend works; podman is rootless-capable and needs no daemon.
  virtualisation.oci-containers.backend = "podman"; # or "docker"

  virtualisation.oci-containers.containers.esign-service = {
    image = "ghcr.io/blinkbitcoin/esign-service:latest"; # pin :<version> in production
    autoStart = true;

    # The whole configuration, as on every other target.
    environmentFiles = [ "/run/secrets/esign.env" ];

    environment = {
      # The image already defaults to this; naming it here is the reminder
      # that a production posture refuses demo hosts and the mock provider
      ESIGN_ENV = "production";
      PORT = "4100";
      # Behind a reverse proxy, so the rate limits key on the real client
      TRUST_PROXY = "true";
      DOCUSIGN_PRIVATE_KEY_FILE = "/run/secrets/docusign.pem";
    };

    volumes = [ "/run/secrets/docusign.pem:/run/secrets/docusign.pem:ro" ];

    ports = [ "4100:4100" ];

    # Publish on the loopback interface only when a reverse proxy fronts it:
    # ports = [ "127.0.0.1:4100:4100" ];
    extraOptions = [ "--health-cmd=wget -qO- http://127.0.0.1:4100/health" ];
  };

  # --- Envelope orchestration (optional) ----------------------------------
  # Set DATABASE_URL in the env file, give the container a database, and
  # apply the schema once per database.
  #
  # A database on the host (services.postgresql.enable = true; and a
  # postgresql.ensureDatabases / ensureUsers pair) is reached from the
  # container over the host address, so the container also needs
  # extraOptions = [ "--network=host" ]; or an explicit podman network. A
  # second oci-containers.containers entry running postgres:15 is the
  # self-contained alternative.
  #
  # The migrate one-shot, run once per database (and after an upgrade that
  # adds a migration), from a root shell on the host:
  #
  #   podman run --rm --env-file /run/secrets/esign.env \
  #     ghcr.io/blinkbitcoin/esign-service:latest node dist/node.js migrate
}
